# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Build Jekyll with Bundler on GitLab
#name: Neither fashionable nor late
#email: your-email@domain.com

# for your document head meta (for Google search results) and in your feed.xml site description.
#description:
# change this to the subpath of your site (e.g., /blog). Leave it empty if you don't need it.
baseurl: "/rmlm.gitlab.io"
# the base hostname & protocol for your site
url: "https://rmlm.gitlab.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge

exclude: [vendor, "Gemfile", "Gemfile.lock", "README.md"]

# Jekyll plugins?
plugins_dir:
- jekyll-feed
- jekyll-sitemap
