# formatted using black

from bibliography import bib

# bnmr peer reviewed conference proceedings
proceedings = [
    bib(
        author="H. Saadaoui",
        title="BnmrOffice: a free software for β-NMR data analysis",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011049",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011049",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-29",
        pub_date="2018-03-01",
    ),
    bib(
        author="S. R. Kreitzman and G. D. Morris",
        title="TRIUMF MuSR and βNMR research facilities",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011056",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011056",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-23",
        pub_date="2018-03-01",
    ),
    bib(
        author="A. Chatzichristos, R. M. L. McFadden, V. L. Karner, D. L. Cortie, C. D. P. Levy, W. A. MacFarlane, G. D. Morris, M. R. Pearson, Z. Salman, and R. F. Kiefl",
        title="Comparison of <sup>8</sup>Li and <sup>9</sup>Li spin relaxation in SrTiO<sub>3</sub> and Pt: a means to distinguish magnetic and electric quadrupolar sources of relaxation",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011048",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011048",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-19",
        pub_date="2018-03-01",
    ),
    bib(
        author="R. M. L. McFadden, A. Chatzichristos, M. H. Dehn, D. Fujimoto, H. Funakubo, A. Gottberg, T. Hitosugi, V. L. Karner, R. F. Kiefl, M. Kurokawa, J. Lassen, C. D. P. Levy, R. Li, G. D. Morris, M. R. Pearson, S. Shiraki, M. Stachura, J. Sugiyama, D. M. Szunyogh, and W. A. MacFarlane",
        title="On the use of <sup>31</sup>Mg for β-detected NMR studies of solids",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011047",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011047",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-15",
        pub_date="2018-03-01",
    ),
    bib(
        author="V. L. Karner, R. M. L. Mcfadden, M. H. Dehn, D. Fujimoto, A. Chatzichristos, G. D. Morris, M. R. Pearson, C. D. P. Levy, A. Reisner, L. H. Tjeng, R. F. Kiefl, and W. A. Macfarlane",
        title="Beta-detected NMR of LSAT and YSZ",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011024",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011024",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-21",
        pub_date="2018-03-01",
    ),
    bib(
        author="V. L. Karner, R. M. L. Mcfadden, A. Chatzichristos, G. D. Morris, M. R. Pearson, C. D. P. Levy, Z. Salman, D. L. Cortie, R. F. Kiefl, and W. A. Macfarlane",
        title="Beta detected NMR of LaAlO<sub>3</sub>",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011023",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011023",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-21",
        pub_date="2018-03-01",
    ),
    bib(
        author="V. L. Karner, T. Liu, I. Mckenzie, A. Chatzichristos, D. L. Cortie, G. D. Morris, R. F. Kiefl, R. M. L. Mcfadden, Z. Fakhraai, M. Stachura, and W. A. Macfarlane",
        title="Exploring the dynamics of glasses using beta detected NMR",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011022",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011022",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-21",
        pub_date="2018-03-01",
    ),
    bib(
        author="J. Sugiyama, I. Umegaki, S. Shiraki, T. Hitosugi, R. M. L. McFadden, D. Wang, V. Karner, G. D. Morris, W. A. MacFarlane, and R. F. Kiefl",
        title="Challenge for detecting the interface between electrode and electrolyte with β-NMR",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011021",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011021",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-14",
        pub_date="2018-03-01",
    ),
    bib(
        author="W. A. MacFarlane, K. H. Chow, M. D. Hossain, V. L. Karner, R. F. Kiefl, R. M. L. McFadden, G. D. Morris, H. Saadaoui, and Z. Salman",
        title="The spin relaxation of <sup>8</sup>Li<sup>+</sup> in gold at low magnetic field",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011020",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011020",
        openacess=True,
        kind="proceeding",
        sub_date="2017-06-23",
        pub_date="2018-03-01",
    ),
    bib(
        author="R. F. Kiefl",
        title="Developments in μSR and β NMR: beyond a muon lifetime",
        journal="JPS Conf. Proc.",
        volume="21",
        pages="011001",
        year="2018",
        month="03",
        day="01",
        doi="10.7566/JPSCP.21.011001",
        openacess=True,
        kind="proceeding",
        note="Yamazaki Prize",
        sub_date="2017-08-28",
        pub_date="2018-03-01",
    ),
    bib(
        author="M. Stachura, R. M. L. McFadden, A. Chatzichristos, M. H. Dehn, A. Gottberg, L. Hemmingsen, A. Jancso, V. L. Karner, R. F. Kiefl, F. H. Larsen, J. Lassen, C. D. P. Levy, R. Li, W. A. MacFarlane, G. D. Morris, S. Pallada, M. R. Pearson, D. Szunyogh, P. W. Thulstrup, and A. Voss",
        title="Towards <sup>31</sup>Mg-β-NMR resonance linewidths adequate for applications in magnesium chemistry",
        journal="Hyperfine Interact.",
        volume="238",
        pages="32",
        year="2017",
        month="02",
        day="14",
        doi="10.1007/s10751-017-1408-8",
        openacess=False,
        kind="proceeding",
        sub_date="2017-02-14",
        pub_date="2017-02-14",
    ),
    bib(
        author="C. D. P. Levy, M. R. Pearson, M. H. Dehn, V. L. Karner, R. F. Kiefl, J. Lassen, R. Li, W. A. MacFarlane, R. M. L. McFadden, G. D. Morris, M. Stachura, A. Teigelhöfer, and A. Voss",
        title="Development of a polarized <sup>31</sup>Mg<sup>+</sup> beam as a spin-1/2 probe for BNMR",
        journal="Hyperfine Interact.",
        volume="237",
        pages="162",
        year="2016",
        month="11",
        day="22",
        doi="10.1007/s10751-016-1372-8",
        openacess=False,
        kind="proceeding",
        sub_date="2016-11-22",
        pub_date="2016-11-22",
    ),
    bib(
        author="W. A. MacFarlane, C. D. P. Levy, M. R. Pearson, T. Buck, K. H. Chow, A. N. Hariwal, R. F. Kiefl, F. H. McGee, G. D. Morris, and D. Wang",
        title="The initial state of optically polarized <sup>8</sup>Li<sup>+</sup> from the β-NMR in bismuth",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012059",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012059",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="F. H. McGee, I. McKenzie, T. Buck, C. R. Daley, J. A. Forrest, M. Harada, R. F. Kiefl, C. D. P. Levy, G. D. Morris, M. R. Pearson, J. Sugiyama, D. Wang, and W. A. MacFarlane",
        title="A brief survey of β-detected NMR of implanted <sup>8</sup>Li<sup>+</sup> in organic polymers",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012039",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012039",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="Z. Salman, K. H. Chow, M. D. Hossain, R. F. Kiefl, C. D. P. Levy, T. J. Parolin, M. R. Pearson, H. Saadaoui, D. Wang, and W. A. MacFarlane",
        title="β-detected nuclear quadrupole resonance and relaxation of <sup>8</sup>Li<sup>+</sup> in sapphire",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012034",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012034",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="W. A. MacFarlane, T. J. Parolin, D. L. Cortie, K. H. Chow, M. D. Hossain, R. F. Kiefl, C. D. P. Levy, R. M. L. McFadden, G. D. Morris, M. R. Pearson, H. Saadaoui, Z. Salman, Q. Song, and D. Wang",
        title="<sup>8</sup>Li<sup>+</sup> β-NMR in the cubic insulator MgO",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012033",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012033",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="R. M. L. McFadden, D. L. Cortie, D. J. Arseneau, T. J. Buck, C.-C. Chen, M. H. Dehn, S. R. Dunsiger, R. F. Kiefl, C. D. P. Levy, C. Li, G. D. Morris, M. R. Pearson, D. Samuelis, J. Xiao, J. Maier, and W. A. MacFarlane",
        title="β-NMR of <sup>8</sup>Li<sup>+</sup> in rutile TiO<sub>2</sub>",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012032",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012032",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="D. Cortie, T. Buck, R. M. L. McFadden, J. Xiao, C. D. P. Levy, M. Dehn, M. Pearson, G. D. Morris, S. R. Dunsiger, R. F. Kiefl, F. J. Rueß, A. Fuhrer, and W. A. MacFarlane",
        title="β-NMR study of a buried Mn δ-doped layer in a silicon host",
        journal="J. Phys.: Conf. Ser.",
        volume="551",
        pages="012023",
        year="2014",
        month="12",
        day="16",
        doi="10.1088/1742-6596/551/1/012023",
        openacess=True,
        kind="proceeding",
        sub_date="2014-10-21",
        pub_date="2014-12-16",
    ),
    bib(
        author="R. F. Kiefl, G. D. Morris, P. Amaudruz, R. Baartman, J. Behr, J. H. Brewer, J. Chakhalian, S. Daviel, J. Doornbos, S. Dunsiger, S. R. Kreitzman, T. Kuo, C. D. P. Levy, R. Miller, M. Olivo, R. Poutissou, G. W. Wight, and A. Zelenski",
        title="Complementarity of low-energy spin polarized radioactive nuclei and muons",
        journal="Physica B",
        volume="289–290",
        pages="640",
        year="2000",
        month="06",
        day="02",
        doi="10.1016/S0921-4526(00)00301-X",
        openacess=False,
        kind="proceeding",
        sub_date="2000-06-02",
        pub_date="2000-06-02",
    ),
    bib(
        author="R. F. Kiefl, W. A. MacFarlane, G. D. Morris, P. Amaudruz, D. Arseneau, H. Azumi, R. Baartman, T. R. Beals, J. Behr, C. Bommas, J. H. Brewer, K. H. Chow, E. Dumont, S. R. Dunsiger, S. Daviel, L. Greene, A. Hatakeyama, R. H. Heffner, Y. Hirayama, B. Hitti, S. R. Kreitzman, C. D. P. Levy, R. I. Miller, M. Olivo, and R. Poutissou",
        title="Low-energy spin-polarized radioactive beams as a nano-scale probe of matter",
        journal="Physica B",
        volume="326",
        pages="189",
        year="2003",
        month="12",
        day="27",
        doi="10.1016/S0921-4526(02)01600-9",
        openacess=False,
        kind="proceeding",
        sub_date="2002-12-27",
        pub_date="2002-12-27",
    ),
    bib(
        author="T. R. Beals, R. F. Kiefl, W. A. MacFarlane, K. M. Nichol, G. D. Morris, C. D. P. Levy, S. R. Kreitzman, R. Poutissou, S. Daviel, R. A. Baartman, and K. H. Chow",
        title="Range straggling of low energy <sup>8</sup>Li<sup>+</sup> in thin metallic films using β-NMR",
        journal="Physica B",
        volume="326",
        pages="205",
        year="2003",
        month="12",
        day="24",
        doi="10.1016/S0921-4526(02)01602-2",
        openacess=False,
        kind="proceeding",
        sub_date="2002-12-24",
        pub_date="2002-12-24",
    ),
    bib(
        author="W. A. MacFarlane, G. D. Morris, K. H. Chow, R. A. Baartman, S. Daviel, S. R. Dunsiger, A. Hatakeyama, S. R. Kreitzman, C. D. P. Levy, R. I. Miller, K. M. Nichol, R. Poutissou, E. Dumont, L. H. Greene, and R. F. Kiefl",
        title="Quadrupolar split <sup>8</sup>Li β-NMR in SrTiO<sub>3</sub>",
        journal="Physica B",
        volume="326",
        pages="209",
        year="2003",
        month="12",
        day="27",
        doi="10.1016/S0921-4526(02)01603-4",
        openacess=False,
        kind="proceeding",
        sub_date="2002-12-27",
        pub_date="2002-12-27",
    ),
    bib(
        author="W. A. MacFarlane, G. D. Morris, T. R. Beals, K. H. Chow, R. A. Baartman, S. Daviel, S. R. Dunsiger, A. Hatakeyama, S. R. Kreitzman, C. D. P. Levy, R. I. Miller, K. M. Nichol, R. Poutissou, and R. F. Kiefl",
        title="<sup>8</sup>Li β-NMR in thin metal films",
        journal="Physica B",
        volume="326",
        pages="213",
        year="2003",
        month="12",
        day="28",
        doi="10.1016/S0921-4526(02)01604-6",
        openacess=False,
        kind="proceeding",
        sub_date="2002-12-28",
        pub_date="2002-12-28",
    ),
    bib(
        author="C. D. P. Levy, A. Hatakeyama, Y. Hirayama, R. F. Kiefl, R. Baartman, J. A. Behr, H. Izumi, D. Melconian, G. D. Morris, R. Nussbaumer, M. Olivo, M. Pearson, R. Poutissou, and G. W. Wight",
        title="Polarized radioactive beam at ISAC",
        journal="Nucl. Instrum. Methods Phys. Res., Sect. B",
        volume="204",
        pages="689",
        year="2003",
        month="01",
        day="30",
        doi="10.1016/S0168-583X(03)00485-3",
        openacess=False,
        kind="proceeding",
        sub_date="2003-01-30",
        pub_date="2003-01-30",
    ),
    bib(
        author="R. F. Kiefl, W. A. MacFarlane, P. Amaudruz, D. Arseneau, R. Baartman, T. R. Beals, J. Behr, J. Brewer, S. Daviel, A. Hatakeyama, B. Hitti, S. R. Kreitzman, C. D. P. Levy, R. Miller, M. Olivo, R. Poutissou, G. D. Morris, S. R. Dunsiger, R. Heffner, K. H. Chow, Y. Hirayama, H. Izumi, C. Bommas, E. Dumont, and L. H. Greene",
        title="Low energy spin polarized radioactive beams as a probe of thin films and interfaces",
        journal="Nucl. Instrum. Methods Phys. Res., Sect. B",
        volume="204",
        pages="682",
        year="2003",
        month="01",
        day="30",
        doi="10.1016/S0168-583X(03)00479-8",
        openacess=False,
        kind="proceeding",
        sub_date="2003-01-30",
        pub_date="2003-01-30",
    ),
    bib(
        author="K. H. Chow, Z. Salman, R. F. Kiefl, W. A. MacFarlane, C. D. P. Levy, P. Amaudruz, R. Baartman, J. Chakhalian, S. Daviel, Y. Hirayama, A. Hatakeyama, D. J. Arseneau, B. Hitti, S. R. Kreitzman, G. D. Morris, R. Poutissou, and E. Reynard",
        title="The new β-NMR facility at TRIUMF and applications in semiconductors",
        journal="Physica B",
        volume="340–342",
        pages="1151",
        year="2003",
        month="12",
        day="03",
        doi="10.1016/j.physb.2003.09.101",
        openacess=False,
        kind="proceeding",
        sub_date="2003-12-03",
        pub_date="2003-12-03",
    ),
    bib(
        author="R. I. Miller, D. Arseneau, K. H. Chow, S. Daviel, A. Engelbertz, M. D. Hossain, T. Keeler, R. F. Kiefl, S. Kreitzman, C. D. P. Levy, P. Morales, G. D. Morris, W. A. MacFarlane, T. J. Parolin, R. Poutissou, H. Saadaoui, Z. Salman, D. Wang, and J. Y. T. Wei",
        title="Nuclear spin relaxation of <sup>8</sup>Li in a thin film of La<sub>0.67</sub>Ca<sub>0.33</sub>MnO<sub>3</sub>",
        journal="Physica B",
        volume="374–375",
        pages="30",
        year="2006",
        month="01",
        day="05",
        doi="10.1016/j.physb.2005.11.009",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-01-05",
    ),
    bib(
        author="T. A. Keeler, Z. Salman, K. H. Chow, B. Heinrich, M. D. Hossain, B. Kardasz, R. F. Kiefl, S. R. Kreitzman, W. A. MacFarlane, O. Mosendz, T. J. Parolin, and D. Wang",
        title="Hyperfine fields in a Ag/Fe magnetic multilayer probed with low energy spin polarized <sup>8</sup>Li",
        journal="Physica B",
        volume="374–375",
        pages="79",
        year="2006",
        month="01",
        day="06",
        doi="10.1016/j.physb.2005.11.020",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-01-06",
    ),
    bib(
        author="D. Wang, M. D. Hossain, Z. Salman, D. Arseneau, K. H. Chow, S. Daviel, T. A. Keeler, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, G. D. Morris, R. I. Miller, W. A. MacFarlane, T. J. Parolin, and H. Saadaoui",
        title="β-detected NMR of <sup>8</sup>Li in the normal state of 2H-NbSe<sub>2</sub>",
        journal="Physica B",
        volume="374–375",
        pages="239",
        year="2006",
        month="01",
        day="10",
        doi="10.1016/j.physb.2005.11.064",
        arxiv="cond-mat/0511357",
        arxiv_cat="cond-mat.str-el",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-01-10",
    ),
    bib(
        author="K. H. Chow, Z. Salman, W. A. MacFarlane, B. Campbell, T. A. Keeler, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, G. D. Morris, T. J. Parolin, S. Daviel, and Z. Yamani",
        title="Early <sup>8</sup>Li<sup>+</sup> β-NMR investigations in GaAs and Ge",
        journal="Physica B",
        volume="374–375",
        pages="415",
        year="2006",
        month="02",
        day="17",
        doi="10.1016/j.physb.2005.11.120",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-02-17",
    ),
    bib(
        author="T. J. Parolin, Z. Salman, J. Chakhalian, D. Wang, T. A. Keeler, M. D. Hossain, R. F. Kiefl, K. H. Chow, G. D. Morris, R. I. Miller, and W. A. MacFarlane",
        title="β-NMR of palladium foil",
        journal="Physica B",
        volume="374–375",
        pages="419",
        year="2006",
        month="01",
        day="05",
        doi="10.1016/j.physb.2005.11.121",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-01-05",
    ),
    bib(
        author="Z. Salman, R. F. Kiefl, K. H. Chow, W. A. MacFarlane, S. R. Kreitzman, D. J. Arseneau, S. Daviel, C. D. P. Levy, Y. Maeno, and R. Poutissou",
        title="Beta-detected NQR in zero field with a low energy beam of <sup>8</sup>Li<sup>+</sup>",
        journal="Physica B",
        volume="374–375",
        pages="468",
        year="2006",
        month="02",
        day="10",
        doi="10.1016/j.physb.2005.11.168",
        arxiv="cond-mat/0511356",
        arxiv_cat="cond-mat.str-el",
        openacess=False,
        kind="proceeding",
        sub_date="2005-11-07",
        pub_date="2006-02-10",
    ),
    bib(
        author="T. Dunlop, A. I. Mansour, Z. Salman, K. H. Chow, I. Fan, J. Jung, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, W. A. MacFarlane, G. Morris, and T. J. Parolin",
        title="<sup>8</sup>Li in GaAs studied with β-NMR",
        journal="Physica B",
        volume="401–402",
        pages="254",
        year="2007",
        month="09",
        day="02",
        doi="10.1016/j.physb.2007.08.160",
        openacess=False,
        kind="proceeding",
        sub_date="2007-08-20",
        pub_date="2007-09-02",
    ),
    bib(
        author="A. I. Mansour, G. D. Morris, Z. Salman, K. H. Chow, T. Dunlop, J. Jung, I. Fan, W. A. MacFarlane, R. F. Kiefl, T. J. Parolin, H. Saadaoui, D. Wang, M. D. Hossain, Q. Song, M. Smadella, O. Mosendz, B. Kardasz, and B. Heinrich",
        title="Development of the <sup>8</sup>Li cross-relaxation technique: applications in semiconductors and other condensed matter systems",
        journal="Physica B",
        volume="401–402",
        pages="662",
        year="2007",
        month="09",
        day="11",
        doi="10.1016/j.physb.2007.09.046",
        openacess=False,
        kind="proceeding",
        sub_date="2007-08-20",
        pub_date="2007-09-11",
    ),
    bib(
        author="Q. Song, K. H. Chow, M. Egilmez, I. Fan, M. D. Hossain, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, G. D. Morris, T. J. Parolin, M. R. Pearson, Z. Salman, H. Saadaoui, M. Smadella, D. Wang, N. J. C. Ingle, and W. A. MacFarlane",
        title="Spin lattice relaxation of <sup>8</sup>Li in a ferromagnetic EuO epitaxial thin film",
        journal="Physica B",
        volume="404",
        pages="619",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.110",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="H. Saadaoui, G. D. Morris, K. H. Chow, M. D. Hossain, C. D. P. Levy, T. J. Parolin, M. R. Pearson, Z. Salman, M. Smadella, Q. Song, D. Wang, P. J. Hentges, L. H. Greene, R. F. Kiefl, and W. A. MacFarlane",
        title="Search for time-reversal symmetry breaking order at the (110) interface of YBa<sub>2</sub>Cu<sub>3</sub>O<sub>7–δ</sub> using βNMR",
        journal="Physica B",
        volume="404",
        pages="724",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.188",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="H. Saadaoui, W. A. MacFarlane, Z. Salman, G. D. Morris, K. H. Chow, I. Fan, P. Fournier, M. D. Hossain, T. A. Keeler, S. R. Kreitzman, C. D. P. Levy, A. I. Mansour, R. I. Miller, T. J. Parolin, M. R. Pearson, Q. Song, D. Wang, and R. F. Kiefl",
        title="β-NMR investigation of the vortex lattice near the interface of silver and Pr<sub>1.85</sub>Ce<sub>0.15</sub>CuO<sub>4–δ</sub> thin films",
        journal="Physica B",
        volume="404",
        pages="727",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.187",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="H. Saadaoui, W. A. MacFarlane, G. D. Morris, Z. Salman, K. H. Chow, I. Fan, M. D. Hossain, R. Liang, A. I. Mansour, T. J. Parolin, M. Smadella, Q. Song, D. Wang, and R. F. Kiefl",
        title="Vortex lattice disorder in YBa<sub>2</sub>Cu<sub>3</sub>O<sub>7–δ</sub> studied with β-NMR",
        journal="Physica B",
        volume="404",
        pages="730",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.229",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="Q. Song, K. Chow, R. Miller, I. Fan, M. Hossain, R. Kiefl, S. Kreitzman, C. Levy, T. Parolin, M. Pearson, Z. Salman, H. Saadaoui, M. Smadella, D. Wang, K. Yu, X. Liu, J. Furdyna, and W. MacFarlane",
        title="Beta-detected NMR study of the local magnetic field in epitaxial GaAs:Mn",
        journal="Physica B",
        volume="404",
        pages="892",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.143",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="I. Fan, K. Chow, T. Parolin, M. Egilmez, M. Hossain, J. Jung, T. Keeler, R. Kiefl, S. Kreitzman, C. Levy, R. Ma, G. Morris, M. Pearson, H. Saadaoui, Z. Salman, M. Smadella, Q. Song, D. Wang, M. Xu, and W. MacFarlane",
        title="β-NMR of a thin Pt film",
        journal="Physica B",
        volume="404",
        pages="906",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.139",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="A. I. Mansour, G. D. Morris, Z. Salman, K. H. Chow, T. Dunlop, J. Jung, I. Fan, W. A. MacFarlane, R. F. Kiefl, T. J. Parolin, H. Saadaoui, D. Wang, M. D. Hossain, Q. Song, M. Smadella, O. Mosendz, B. Kardasz, B. Heinrich, C. D. P. Levy, and M. R. Pearson",
        title="Cross-relaxation of <sup>8</sup>Li<sup>+</sup> in copper",
        journal="Physica B",
        volume="404",
        pages="910",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.138",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="M. D. Hossain, H. Saadaoui, T. J. Parolin, Q. Song, D. Wang, M. Smadella, K. H. Chow, M. Egilmez, I. Fan, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, G. D. Morris, M. R. Pearson, Z. Salman, and W. A. MacFarlane",
        title="The spin lattice relaxation of <sup>8</sup>Li in simple metals",
        journal="Physica B",
        volume="404",
        pages="914",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.157",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="T. J. Parolin, Z. Salman, J. Chakhalian, Q. Song, K. H. Chow, G. D. Morris, M. Egilmez, I. Fan, M. D. Hossain, T. A. Keeler, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, A. I. Mansour, R. I. Miller, M. R. Pearson, H. Saadaoui, M. Smadella, D. Wang, M. Xu, and W. A. MacFarlane",
        title="Hyperfine fields in thin Pd films by beta-detected NMR",
        journal="Physica B",
        volume="404",
        pages="917",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.137",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="D. Wang, Z. Salman, K. H. Chow, I. Fan, M. D. Hossain, T. A. Keeler, R. F. Kiefl, C. D. P. Levy, A. I. Mansour, G. D. Morris, M. R. Pearson, T. J. Parolin, H. Saadaoui, M. Smadella, Q. Song, and W. A. MacFarlane",
        title="Nuclear spin relaxation/resonance of <sup>8</sup>Li in Al",
        journal="Physica B",
        volume="404",
        pages="920",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.136",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="M. Smadella, Z. Salman, K. H. Chow, M. Egilmez, I. Fan, M. D. Hossain, R. F. Kiefl, S. R. Kreitzman, C. D. P. Levy, W. A. MacFarlane, A. I. Mansour, G. D. Morris, T. J. Parolin, M. Pearson, H. Saadaoui, Q. Song, and D. Wang",
        title="Surface dependent structural phase transition in SrTiO<sub>3</sub> observed with spin relaxation of <sup>8</sup>Li",
        journal="Physica B",
        volume="404",
        pages="924",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.135",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="C. D. P. Levy, M. R. Pearson, G. D. Morris, J. Lassen, K. H. Chow, M. D. Hossain, R. F. Kiefl, R. Labbé, W. A. MacFarlane, T. J. Parolin, L. Root, H. Saadaoui, M. Smadella, and D. Wang",
        title="Polarisation of a spin-1⁄2 β-NMR probe <sup>11</sup>Be using collinear laser optical pumping",
        journal="Physica B",
        volume="404",
        pages="1010",
        year="2009",
        month="12",
        day="06",
        doi="10.1016/j.physb.2008.11.205",
        openacess=False,
        kind="proceeding",
        sub_date="2008-11-15",
        pub_date="2008-12-06",
    ),
    bib(
        author="C. D. P. Levy, M. R. Pearson, G. D. Morris, K. H. Chow, M. D. Hossain, R. F. Kiefl, R. Labbé, J. Lassen, W. A. MacFarlane, T. J. Parolin, H. Saadaoui, M. Smadella, Q. Song, and D. Wang",
        title="Development of the collinear laser beam line at TRIUMF",
        journal="Hyperfine Interact.",
        volume="196",
        pages="287",
        year="2010",
        month="01",
        day="19",
        doi="10.1007/s10751-009-0148-9",
        openacess=False,
        kind="proceeding",
        sub_date="2010-01-19",
        pub_date="2010-01-19",
    ),
    bib(
        author="A. Voss, M. R. Pearson, J. Billowes, F. Buchinger, K. H. Chow, J. E. Crawford, M. D. Hossein, R. F. Kiefl, C. D. P. Levy, W. A. MacFarlane, E. Mané, G. D. Morris, T. J. Parolin, H. Saadaoui, Z. Salman, M. Smadella, Q. Song, and D. Wang",
        title="The development of pure β-NQR techniques for measurements of nuclear ground state quadrupole moments in lithium isotopes",
        journal="J. Phys.: Conf. Ser.",
        volume="312",
        pages="092063",
        year="2011",
        month="09",
        day="23",
        doi="10.1088/1742-6596/312/9/092063",
        openacess=True,
        kind="proceeding",
        sub_date="2011-07-27",
        pub_date="2011-09-23",
    ),
    bib(
        author="K. H. Chow, A. I. Mansour, I. Fan, G. D. Morris, Z. Salman, T. Dunlop, W. A. MacFarlane, R. F. Kiefl, H. Saadaoui, O. Mosendz, B. Kardasz, B. Heinrich, J. Jung, C. D. P. Levy, M. R. Pearson, T. J. Parolin, D. Wang, M. D. Hossain, Q. Song, and M. Smadella",
        title="Observing cross-relaxation with depth-resolved <sup>8</sup>Li β-NMR",
        journal="Phys. Proc.",
        volume="30",
        pages="16",
        year="2012",
        month="06",
        day="01",
        doi="10.1016/j.phpro.2012.04.030",
        openacess=True,
        kind="proceeding",
        sub_date="2012-06-01",
        pub_date="2012-06-01",
    ),
    bib(
        author="Q. Song, K. H. Chow, M. D. Hossain, R. F. Kieﬂ, G. D. Morris, C. D. P. Levy, H. Saadaoui, M. Smadella, D. Wang, B. Kardasz, B. Heinrich, and W. A. MacFarlane",
        title="β-detected NMR study of semi-insulating GaAs",
        journal="Phys. Proc.",
        volume="30",
        pages="227",
        year="2012",
        month="06",
        day="01",
        doi="10.1016/j.phpro.2012.04.079",
        openacess=True,
        kind="proceeding",
        sub_date="2012-06-01",
        pub_date="2012-06-01",
    ),
    bib(
        author="D. Wang, K. H. Chow, M. Smadella, M. D. Hossain, W. A. MacFarlane, G. D. Morris, O. Ofer, E. Morenzoni, Z. Salman, H. Saadaoui, Q. Song, and R. F. Kiefl",
        title="Use of the strong collision model to calculate spin relaxation",
        journal="Phys. Proc.",
        volume="30",
        pages="38",
        year="2012",
        month="06",
        day="01",
        doi="10.1016/j.phpro.2012.04.035",
        openacess=True,
        kind="proceeding",
        sub_date="2012-06-01",
        pub_date="2012-06-01",
    ),
    bib(
        author="O. Ofer, K. H. Chow, I. Fan, M. Egilmez, T. J. Parolin, M. D. Hossain, J. Jung, Z. Salman, R. F. Kiefl, C. D. P. Levy, G. D. Morris, M. R. Pearson, H. Saadaoui, Q. Song, D. Wang, and W. A. MacFarlane",
        title="<sup>8</sup>Li<sup>+</sup> Knight shift and resonance in the enhanced paramagnet platinum studied by βNMR",
        journal="Phys. Proc.",
        volume="30",
        pages="356",
        year="2012",
        month="06",
        day="01",
        doi="10.1016/j.phpro.2012.04.062",
        openacess=True,
        kind="proceeding",
        sub_date="2012-06-01",
        pub_date="2012-06-01",
    ),
    bib(
        author="Q. Song, K. H. Chow, R. I. Miller, I. Fan, M. D. Hossain, R. F. Kiefl, G. D. Morris, S. R. Kreitzman, C. D. P. Levy, T. J. Parolin, M. R. Pearson, Z. Salman, H. Saadaoui, M. Smadella, D. Wang, K. M. Yu, X. Liu, J. K. Furdyna, and W. A. MacFarlane",
        title="β-Detected NMR search for magnetic phase separation in epitaxial GaAs:Mn",
        journal="Phys. Proc.",
        volume="30",
        pages="174",
        year="2012",
        month="06",
        day="01",
        doi="10.1016/j.phpro.2012.04.066",
        openacess=True,
        kind="proceeding",
        sub_date="2012-06-01",
        pub_date="2012-06-01",
    ),
]
